version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - data-visualization-network
    depends_on:
      - backend
      - frontend
      - postgres

  backend:
    build:
      context: ./data-visualization
      dockerfile: Dockerfile
    container_name: data-visualization-backend
    tty: true
    restart: always
    volumes:
      - "./:/var/www/html"
    networks:
      - data-visualization-network

  frontend:
    build:
      context: ./data-visualization-frontend
      dockerfile: Dockerfile
    container_name: data-visualization-frontend
    tty: true
    restart: always
    volumes:
      - ./:/home/node/DATA-VISUALIZATION
    ports:
      - 3000:3000
    networks:
      - data-visualization-network

  postgres:
    image: postgres:16.1-alpine
    container_name: data-visualization-postgres
    environment:
      - POSTGRES_DB=data-viz
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    networks:
      - data-visualization-network

networks:
  data-visualization-network:
    driver: bridge  

volumes:
  postgres:
    driver: local