name: frontend-docker-build

on:
  push:
    branches: [main]
    paths:
      - 'data-viz-frontend/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./data-viz-frontend
          file: ./data-viz-frontend/Dockerfile
          push: true
          tags: ghcr.io/ngtrdai/data-viz/data-viz-frontend:latest
